# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_qt <- function(p, nu, delta) {
    .Call('_regtolerance_rcpp_qt', PACKAGE = 'regtolerance', p, nu, delta)
}

rcpp_qchisq <- function(p, nu, delta) {
    .Call('_regtolerance_rcpp_qchisq', PACKAGE = 'regtolerance', p, nu, delta)
}

integral <- function(l, p, k, d) {
    .Call('_regtolerance_integral', PACKAGE = 'regtolerance', l, p, k, d)
}

